name: Build Left
run: |
    west build -s zmk/app -d build/left \
      -b xiao_ble \
      -- -DSHIELD=roBa \
         -DZMK_CONFIG=$GITHUB_WORKSPACE/config \
         -DZMK_CONFIG_FILE=roBa_L.conf

name: Build Right
run: |
    west build -s zmk/app -d build/right \
      -b xiao_ble \
      -- -DSHIELD=roBa \
         -DZMK_CONFIG=$GITHUB_WORKSPACE/config \
         -DZMK_CONFIG_FILE=roBa_R.conf
